baseURL = "https://www.decentinternet.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Decent Internet"
theme = "child-theme"
googleAnalytics = "UA-123456789-1"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "Articles and resources on how to make the internet accessible, humane and manageable. Some things are code-oriented. Everything is people-oriented."
  homeMetaContent = "Articles and resources on how to make the internet accessible, humane and manageable. <br>Some things are code-oriented. Everything is people-oriented."
  dateFormat = "Jan 2, 2006"
  mainSections = ["post"]

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Archive"
    url = "/archive/"
    weight = 2
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3